### ISSUE TITLE
Shirt designs

### ISSUE THREAD

**Issue by luceos** [tenancy/tenancy#10]
Hey there,

We're looking on setting up an interesting collection of 🤓 **shirts related to Laravel Tenancy. We could use your help with getting some additional inspiration. Once we have shirts printed with your idea we will send you one for free which will include a personal thank you note. 

In addition the idea with **the highest vote will receive 50 euro as price** from me personally via PayPal!

---

We're looking for ideas related to tenancy, tenants, renting etc which can be related back to web development and/or this package. If it's nerdy or funny, please share!

Please also cast your vote on the ideas you like. You are allowed to upvote your own idea.

- One idea per comment.
- An idea has to be pretty clear about the intent and/or suggest implementations; clarify visuals and/or texts needed.
- Use comments to post ideas, if you want to comment on an idea use [Discord](https://laravel-tenancy.com/chat).
- Post as many ideas as you like, but give some effort. Don't spam.
- If a team member receives the highest votes, the second best receives the price.
- By posting your idea you allow us to use it.

**Comment by luceos** [comment]
One of my ideas is to show several tenant buildings, underneath the motto "We power saas tenants" and between the buildings you can see power/electricity surges with one building being on fire 🔥

**Comment by luceos** [comment]
Another idea would be to show a huge building on top of the clouds with the motto

"Raising your saas above the cloud" or "Bring your multi tenant Laravel app to the cloud"

**Comment by miikee-us** [comment]
"Multi-tenancy is the only ten I see"
(with geeky, where's waldo glasses above the quote)

**Comment by waiel** [comment]
Multi-Tenancy: CyberSpace is your limit

**Comment by luceos** [comment]
"We're keeping your tenants safe"

Showing doors with locks or people behind bars

**Comment by luceos** [comment]
"We're the highrise of multi-tenant saas toolkits"

Showing a dominant forward leaning tall building.

**Comment by luceos** [comment]
"Reach for the stars"

Building that rises up to the stars

**Comment by miikee-us** [comment]
"Empowering developers to build secure and scalable apps"

**Comment by TNovalis** [comment]
Multi-Tanancy
[Logo]
Secure. Stable. Scalable.

**Comment by Felli** [comment]
As discussed on Discord @luceos, I liked your second one but with a different motto. :sweat_smile: 

> Another idea would be to show a huge building on top of the clouds with the motto
"Saas in the skies/cloud"

**Comment by luceos** [comment]
3 years, 100 releases, 1 package; Tenancy

Not sure how to visually represent this.

**Comment by miikee-us** [comment]
SAAS toolkits built for the future.
(Toolbox in a cloud)

**Comment by Krato** [comment]
My idea:

Tenancy, Scalable, SaaS (Centered in middle size)
Do you know how to join these words? (centered small size)
We are Devs (Centered Big size | Maybe Coders or Devs)

**Comment by luceos** [comment]
@Krato please split them up so that people can vote on items separately 👍

**Comment by endrureza** [comment]
My idea :

```bash
> run tenancy
```

**Comment by endrureza** [comment]
Another One:

```bash
# su tenancy
```

**Comment by endrureza** [comment]
Could be like this too:

```bash
> artisan tenancy
```

**Comment by Krato** [comment]
Another idea:

Tenancy, Scalable, Laravel (Centered in middle size)
Do you understand? (centered small size)
We are Devs (Centered Big size | Maybe Coders or Devs)

**Comment by Krato** [comment]
Last idea 😅 

Scaffold, Scalable, SaaS
Do you understand?
Laravel Tenancy

**Comment by luceos** [comment]
Based on @Krato latest idea:

"Do you SaaS? It's PaaS with Laravel Tenancy!"

**Comment by luceos** [comment]
"Building awesome SaaS with Laravel Tenancy"

**Comment by luceos** [comment]
I'm not sure we found any viable candidates. We're closing this issue at the end of this week at Friday 28th of July at 21:00 CET. Any entries after that are not considered.

**Comment by luceos** [comment]
"Build for the stars/universe"

**Comment by Felli** [comment]
How about "_Universal SaaS with Laravel Tenancy_"?

**Comment by HelgeSverre** [comment]
"Do you even SaaS brah?"

With an illustration of the tenancy logo with angry goggly eyes and lifting a dumbell composed of two stereotypical skyscraper buildings, yelling at the laravel logo.

**Comment by luceos** [comment]
Totally forgot about this one 😞 

We already decided on a different t-shirt design by @paulotra. As the number of votes are so low I don't think a payout makes sense. I will look into offering an alternative price for all participants. And I will make sure to run this again soon for the second printed artwork design.

Thanks everyone for your participation, it is much appreciated.
