### ISSUE TITLE
Illuminate\Queue\SerializesModels trait cannot hydrate tenant models

### ISSUE THREAD

**Issue by booni3** [tenancy/tenancy#135]
__Setup__
Laravel: 6.12
Running on Vapor (not sure that makes any difference in this case)

__Problem__
The `SerializesModels` trait is  is part of Laravel core and used in quite a few of the core Laravel packages (e.g. Scout).

A collection of models can be added to the job constructor and the trait will Serialize them into the job and then hydrate with up to date data once the job is run.

__Steps To Reproduce__
1. Setup mutli-db t/t
2. Setup a tenant model with the `OnTenant` trait.
3. Setup queue identification driver.
4. Create a dispatchable job that requires the tenant and a collection of tenant models in the constructor and uses the SerializesModels trait.

```php
class SerializesModelsTestJob implements ShouldQueue
{
    use Dispatchable, SerializesModels;

    protected $tenant;
    public $tenant_key = null;
    public $tenant_identifier = null;

    public $models;

    public function __construct($tenant, $models)
    {
        $this->tenant = $tenant;
        $this->tenant_key = $tenant->getTenantKey();
        $this->tenant_identifier = $tenant->getTenantIdentifier();
        
        $this->models = $models;
    }
...
```

5. Dispatch the job

```php
$tenant = Auth::user()->tenant;
$models = \App\TenantModel::query()->take(10)->get();
\App\Jobs\SerializesModelsTestJob::dispatch($tenant, $models);
```

Exception thrown: `Database [tenant] not configured.`

__Stacktrace__
https://sentry.io/share/issue/d4f2c1f593304e95b40aa4d31d1376cb/

**Comment by ArlonAntonius** [comment]
Hi there,

Spent some time on this, this has to do with us serializing the Job in order to take into account custom Queue identifications that people want to use.

We should only try to get the specific keys we actually need for this so we can prevent this from happening. I do see possibilities in this and hope to have time for it this weekend.

**Comment by ArlonAntonius** [comment]
Update:
- There is a fix for this
- Need to double check everything before creating a PR :)

**Comment by albertosgz** [comment]
Hi @ArlonAntonius .

Thank you so much for your work.

It happens to me the same. In my case I'm queueing a notification.

I've upgraded to version 1.0.1 of all the TT packages. I can create tenants, all affects and drivers works. 
But not to queue notifications.
I found a workaround disabling the trait SerializesModels, but it is not the ideal situation.

Ask me any detail you need or any help you need.

Setup: Laravel 7.20 and all TT packages to 1.0.1

**Comment by ArlonAntonius** [comment]
Hi @albertosgz,

Thank you for reporting this to us.

Could you create a new issue for this and possibly add an example repo where we can see the bug?

I'd love to deep dive into this before 1.1 😊

**Comment by albertosgz** [comment]
Thank you @ArlonAntonius for your quickly response.

I've opened #181 .
