### ISSUE TITLE
Cache_driver from file to database

### ISSUE THREAD

**Issue by JGamboa** [tenancy/tenancy#15]
Hello everyone. I have problems to loggin when i change the cache_drive to database.
I make the migration with the laravel documentation and put it on the tenant directory for migrations.
The table it gets created i changed the config/cache.php to

        'database' => [
            'driver' => 'database',
            'table' => 'cache',
            'connection' => 'tenant',
        ],

but when i try to log in on each tenant now i have this error :

 InvalidArgumentException
Database [tenant] not configured.

**Comment by luceos** [comment]
This should be posted to https://github.com/hyn/multi-tenant/issues

thank you.
