### ISSUE TITLE
preventMiddleware not part of Kernel contract

### ISSUE THREAD

**Issue by mblarsen** [tenancy/tenancy#162]
FYI `prependMiddleware()` is not a part of the `Kernel` contract. It is only a method on the implementation  `Illuminate\Foundation\Http\Kernel`.

https://github.com/tenancy/tenancy/blob/9b425bc31294fc529b2fbfb2e66243ef20d90afe/src/Identification/Http/Providers/IdentificationProvider.php#L38-L41

**Meta** do you want these kinds of issues? PRs? or is it just disturbing at this moment?

**Comment by ArlonAntonius** [comment]
Hi there @mblarsen,

I'm well aware of a few of these things that will be looked at before release. It is functionality that is needed for us, assuming that some of these functions exist is completely fine for now and does not worry me.

I'd rather get these types of comments on our Discord, as I can explain why certain things are the way they are and why I might or might not be worried about them.

**Comment by mblarsen** [comment]
Sure, I'll close them here.
