### ISSUE TITLE
Controllers Affect

### ISSUE THREAD

**Issue by hgokturk** [tenancy/tenancy#171]
Thank you very much for great job.
Are you by any chance planning to implement Controllers Affect?

**Comment by Plytas** [comment]
Hello @hgokturk 
I'm not sure what would this affect do. Do you have a potential use case? Maybe it can be solved with other existing affects?

**Comment by hgokturk** [comment]
Assume that the tenancy is identified by customers. For 50 different customers, customer specific business logic must be implemented. What is the proper way to do that?

**Comment by Plytas** [comment]
It depends on how different your business logic is. Maybe it's better to use route affects and route clients to different controllers?

**Comment by hgokturk** [comment]
Then it may need 50 different controllers to be created for 50 customer spesific logic. In a scenario that controller affects are in use, just see below:

- app
-     controllers
-         customer1
-             aController
-             bController
-             cController
-             xController
-         customer2
-             aController
-             bController
-             cController
-             yController

**Comment by Plytas** [comment]
So your idea would be to load same controller from different customer? Wouldn't that be the same as using route affect?

**Comment by hgokturk** [comment]
Yeah, in a way it would be the same. But why not seperate the controllers while all the rest is well seperated as affects?

**Comment by Plytas** [comment]
I'm not dismissing that, just trying to figure out the use case. I will pass this to the team for consideration, but if you're looking for a fast solution route affects would definitely be a valid solution.

**Comment by hgokturk** [comment]
Yeah I definitely get you. Just saying :)

**Comment by sniper7kills** [comment]
Edit: After re-looking at the example, I see its the second case.

Based on the example you provided; I'd recommend the routes affect as well. 

```php
Route::namespace(Tenant::getTenant()->name)->group(function () {
    // Controllers Within The "App\Http\Controllers\[$tenant->name]" Namespace
});
```

This would reduce the amount of logic having to be run, and you only need to register the routes once as all of the controllers appear to exist for each tenant.

In the event the goal is to have these controllers extended from a "default" logic controller and only extend the controllers that have specific logic, I would agree a controllers effect should be looked into as it would allow you to check if a tenant specific controller exists and if not use the default.

**Comment by ArlonAntonius** [comment]
Hi there,

I don't see the exact use case for this at this moment. The solution provided by @sniper7kills seems like the perfect solution to this problem in my opinion. If there's a more detailed use case later on or if the situation has changed, we can revisit this.
