### ISSUE TITLE
Database hooks not firing

### ISSUE THREAD

**Issue by Tofandel** [tenancy/tenancy#184]
I have `tenancy/tenancy` installed, and I'm trying to get the mysql driver to work, I have lifecycle hooks setup (And tested) but it seems when the lifecycle hooks are fired the `Tenancy\Hooks\Database\Events\Drivers\Configuring` event is not and as a result the database for the tenant is not being created

Is there something not documented or something I am missing like the need to manually register the providers?

Also it seems there is no way to disable the creation of a database if the  `Configuring` event fire like it's possible to do with the `ConfigureDatabaseMutation` and in some cases I would needto skip the creation of the database (without skipping the migrations)

**Comment by ArlonAntonius** [comment]
Hi there @Tofandel,

This is probably caused by you not registering the appropriate Service Providers. When you're using `tenancy/tenancy`, you're responsible for registering the service providers of the packages you would like to use (as it's really difficult for us to simply assume that you're going to use X).

Please make sure you have the `Tenancy\Hooks\Database\Provider` and `Tenancy\Database\Drivers\Mysql\Provider` registered in case you want to use the `MySQL` Database driver.

**Comment by Tofandel** [comment]
@ArlonAntonius That's what I was suspecting thanks :+1: 
I think adding the name of the providers you need to register in the documentation of each module is a good idea as there isn't a single indication about it except a general indication in the install section

> After you've installed tenancy/tenancy make sure you register the Affects and Hooks you wish to use. You do this by simply registering the respective Providers.

Or at least a list of all the providers in the install sections so we can just copy paste it and comment them out for convenience

Here is the list of all of them, I don't think I forgot any

```php

    'providers' => [
         // ...

        /*
         * Package Service Providers...
         */
        Tenancy\Affects\Broadcasts\Provider::class,
        Tenancy\Affects\Cache\Provider::class,
        Tenancy\Affects\Configs\Provider::class,
        Tenancy\Affects\Connections\Provider::class,
        Tenancy\Affects\Filesystems\Provider::class,
        Tenancy\Affects\Logs\Provider::class,
        Tenancy\Affects\Mails\Provider::class,
        Tenancy\Affects\Models\Provider::class,
        Tenancy\Affects\Routes\Provider::class,
        Tenancy\Affects\URLs\Provider::class,
        Tenancy\Affects\Views\Provider::class,

        Tenancy\Hooks\Database\Provider::class,
        Tenancy\Hooks\Migration\Provider::class,
        Tenancy\Hooks\Hostname\Provider::class,

        Tenancy\Database\Drivers\Mysql\Provider::class,
        Tenancy\Database\Drivers\Sqlite\Provider::class,
         // ...
    ]
```
