### ISSUE TITLE
Configure seeder doesn't pass arguments & doesn't set tenant

### ISSUE THREAD

**Issue by Tofandel** [tenancy/tenancy#185]
There seems to be an issue within the `ConfigureSeeder` hook

As it doesn't switch the tenant by default, within the Seeds, we cannot retrieve the Tenant that is being configured unless explicitly calling `Tenancy::setTenant($event->event->tenant)` but this causes the issue of not being able to switch back as the seeds are run after
I think the ConfigureSeeder should switch the tenant before the event and switch it back after it automatically

It would also be nice to add the ability to pass parameters to the seed classes so they can use other params

## Actual
```php
<?php

namespace App\Listeners\Tenants;

use PromotionSeeder;
use Tenancy\Hooks\Migration\Events\ConfigureSeeds;

class ConfigureTenantSeeds {
    public function handle(ConfigureSeeds $event) {
        Tenancy::setTenant($event->event->tenant); // If we don't call this tenant will be null in the next call
        $event->seed(PromotionSeeder::class);
        // And then we cannot revert to no tenant after the seeder is executed
    }
}


class PromotionSeeder extends Seeder {
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        /**
         * @var Tenant $tenant
         */
        $tenant = Tenancy::getTenant();
        // Do something with tenant
   }
}
```
## Expected
```php
class ConfigureTenantSeeds {
    public function handle(ConfigureSeeds $event) {
        $event->seed(PromotionSeeder::class, $event->event->tenant);
    }
}

class PromotionSeeder extends Seeder {
    /**
     * Run the database seeds.
     * @var Tenant $tenant
     * @return void
     */
    public function run($tenant = null) {
       //Do something related to tenant
   }
}
```

**Comment by fletch3555** [comment]
These seeder classes are simply Laravel seeders, and therefore need to follow the same structure.  In this case, the only way to pass arguments into the run method is to override it to accept an argument.  Laravel won't pass any values, so this would likely break.  https://github.com/laravel/framework/blob/7.x/src/Illuminate/Database/Seeder.php#L135

As an alternative, you can get the tenant by using the configured tenant connection.  Something like this:

```
$tenant = Tenant::find(config('database.connections.tenant.database'));
```

**Comment by Tofandel** [comment]
I don't see how the fact that laravel doesn't pass arguments to seeders is relevant, it doesn't mean we can't have it in this package optionally, people are free to overwrite how the seeder is called, eg: https://stackoverflow.com/a/32921227/2977175

But if they do the problem is that this package does not offer this possibility at all. Calling the ->seed() function should just proxy it entirely and not just one argument


This line
`$tenant = Tenant::find(config('database.connections.tenant.database'));`

Does also not work if you do not set

`protected $connection = 'mysql'` on the tenant model

**Comment by Tofandel** [comment]
Maybe it was time to fix the missing feature upstream
https://github.com/laravel/framework/pull/33737

As such I modified my PR to use invoke with arguments like it used to do

So #186  can be released as well even if laravel 8.x is not released yet but until it is it requires overwriting the __invoke method of the seeders to pass arguments to `run` for it to actually pass the arguments

```php
class MySeeder extends Seeder {
    public function run(InjectedDeps $myDep, $arg1, $arg2) {

    }

     /**
     * Run the database seeds.
     *
     * @param mixed ...$params
     * @return mixed
     *
     * @throws \InvalidArgumentException
     */
    public function __invoke( ...$params )
    {
        if (! method_exists($this, 'run')) {
            throw new InvalidArgumentException('Method [run] missing from '.get_class($this));
        }

        return isset($this->container)
                    ? $this->container->call([$this, 'run'], $params)
                    : $this->run(...$params);
    }
}
```

**Comment by ArlonAntonius** [comment]
Closing this as it's not really an issue at this moment. It's an idea which we really appreciate and we will visit this again next month.
