### ISSUE TITLE
How to stop Migrations running on Delete

### ISSUE THREAD

**Issue by bretto36** [tenancy/tenancy#190]
Hi All

Thanks for the great package. How can i prevent the system from throwing an exception "Access denied for user 'demo2'@'172.20.0.6' ' When the tenant is deleted, it runs the DB Drop -> then tries to do the migrations. 

I understand it doing the migrations by default on Create and Update, but not sure why it would try and run them on Delete

Is there a way to change the Event Listener structure so it doesn't call migrations on delete?

**Comment by bretto36** [comment]
I keep doing this. Writing out the issue then helps me solve it. 

For anyone else add this to the ConfigureMigrations event listener


```
 if ($event->event instanceof Deleted) {
     $event->disable();

     return;
}

// Add migrations for created and update
```

**Comment by sneakylenny** [comment]
Very confusing, why would it want to migrate on deletion? Is this a bug?
A rollback would make more sense.

**Comment by bkintanar** [comment]
https://tenancy.dev/docs/tenancy/2.x/hooks-database#mutations-example

There's an example in the site on how to disable database migration upon deletion.
