### ISSUE TITLE
Upgrade to Laravel8

### ISSUE THREAD

**Issue by ricardosierra** [tenancy/tenancy#191]
__Description__

..

---

__Actual behavior__

..

__Expected behavior__

..

---
__Information__

- tenancy/tenancy version:
- laravel version:
- database driver and version:
- webserver software and version:
- php version:

---

__tenancy.php config__

```php

```

---

__Error log__

```text

```

**Comment by fletch3555** [comment]
We're working on it.  Stay tuned!
