### ISSUE TITLE
Override config per tenant

### ISSUE THREAD

**Issue by luceos** [tenancy/tenancy#2]
With `hyn/multi-tenant` currently overriding the configuration files is done using config files in the tenant directory. When using a cloud solution like S3 this becomes a huge complication due to these configuration files being loaded on every single request.

As an alternative we need to create a solution that allows us to override configuration settings per tenant without limiting this to one specific method.

- Store in a system database table.
- Request and cache from an API endpoint (with authorization).
- Load from etcd or some other key value store; perhaps even redis

**Comment by JGamboa** [comment]
i dont know if i understand correct.
But i use the same bucket to for all the tenants, i just create a directory inside with the uuid of the tenant and inside i put the files of each tenant.

**Comment by luceos** [comment]
> But i use the same bucket to for all the tenants, i just create a directory inside with the uuid of the tenant and inside i put the files of each tenant.

@JGamboa thanks for your input. I'm fully aware this is how it works with hyn, the question posed is how to improve storage resolving with the successor. In hyn an issue existed (but was fixed) that would hit the storage API unnecessarily every time the storage adapter for the tenant was instantiated. This issue exists to prevent the same from occurring in the successor.
