### ISSUE TITLE
Add initial caching

### ISSUE THREAD

**Issue by luceos** [tenancy/tenancy#20]
h/m offers (a bare level of) caching, we should see whether this is possible with the current resolver functionality too.

**Comment by ArlonAntonius** [comment]
This was done in [`108ae69`](108ae69e20f36315a5c6b5e9110baa927bcfa4ee) right?

**Comment by luceos** [comment]
This is not about the affects, but about tenant identification caching. I'm not sure we're able to offer something right now. Let's close this as is.
