### ISSUE TITLE
MYSQL 8.x username length

### ISSUE THREAD

**Issue by sniper7kills** [tenancy/tenancy#214]
T/T Packages Installed:
```
tenancy/affects-connections        v1.2.0   The tenancy/tenancy connections mutations
tenancy/db-driver-mysql            v1.2.0   The tenancy/tenancy database driver for mysql
tenancy/framework                  v1.2.0   Creating multi tenant saas from your Laravel app with ease
tenancy/hooks-database             v1.2.0   The tenancy/tenancy database mutations
tenancy/hooks-migration            v1.2.0   The tenancy/tenancy migration mutations
```
PHP Version: 7.4.11
MYSQL Version: 8.0.22

When the tenant model is using UUID's for its primary key and without changing any defaults regarding a tenant's mysql database username, the username used is over 32 characters.

```Illuminate/Database/QueryException with message 'SQLSTATE[HY000]: General error: 1470 String '475dfebc-c497-4929-8448-bf55c1879d51' is too long for user name (should be no longer than 32) (SQL: CREATE USER IF NOT EXISTS `475dfebc-c497-4929-8448-bf55c1879d51`@'%' IDENTIFIED BY 'be9ff207c959cfa3e0df7b12d8c50b49')```

---

One should expect that the package will truncate the username generated to ensure that a username is not longer than 32 characters.

One simple solution would be to check if the generated username is > 32 characters. If not, create a MD5 hash of that username, which should result in exactly 32 characters for the username.

**Comment by ulrikhansen0** [comment]
+1

**Comment by ArlonAntonius** [comment]
Hi there,

We discussed this internally (and totally forgot to document this on GitHub) and decided that this is outside the scope of the package. When we start doing this type of adjustment to the package, we will end up with opinionated code more and more.

With the Tenancy ecosystem, we provide you with a lot of things that make it easy to create a multi-tenant application. We try to code things in a way that first the Laravel ecosystem and through that also assume some defaults. Laravel's default for an identifier is a normal id int, and I think that will be plenty for a lot of people. If you decide to custom the logic behind the naming of the database, that's really up to you.

I'm 100% up for a PR that adds this part regarding the MySQL Database name in the documentation. If we would start building in this type of validation, we will end up with way more limited systems and we might even hurt people who (just like you guys) are doing more complex custom setups, where we accidentally made sure that they can't do the things that they want.
