### ISSUE TITLE
Single connection pool

### ISSUE THREAD

**Issue by mbnoimi** [tenancy/tenancy#225]
Can I use **tenancy** for multi-tenant app uses a single connection pool?
I don't want to create a connection pool per tenant (just want a single connection pool for multi-tenant)
In PostgreSQL usually we use a schema per tenant which means the app uses a single database with multi schemas.

**Comment by sniper7kills** [comment]
I'm not familiar with PostgreSQL and its use of schema's unfortunately, but I'll do my best to help from a MySQL perspective.

We are currently in the process of adding a PostgreSQL driver to the T/T ecosystem, so stay tuned for that.

With T/T there is no requirement to change anything with your connections. (Just don't use the affects connection package).
I'll reach out to the team, and get someone with more PostgreSQL to try to provide some guidance, but could you provide me any example of what in theory you are looking to change once a tenant is identified?

**Comment by fletch3555** [comment]
@mbnoimi , can you elaborate on what you mean by "connection pool"? Are you referring to a postgres feature or a php/laravel feature?  By default, laravel doesn't do any pooling for it's database connections (as far as I'm aware at least), so if you're using some configuration or package for this, we would need to know what it is.

If you are simply referring to the named connections that laravel uses (i.e. this package can create a "tenant" connection), then as @sniper7kills said, just don't use AffectsConnection, and it'll all use the same connection.  Having said that, if you want multiple schemas, what's the harm in having a "tenant" connection point directly at it?

Sounds like premature optimization, but I'm not familiar with your project or its requirements/timeline

**Comment by mbnoimi** [comment]
@sniper7kills 
> but could you provide me any example of what in theory you are looking to change once a tenant is identified?

https://blog.arkency.com/multitenancy-with-postgres-schemas-key-concepts-explained/

**Comment by mbnoimi** [comment]
@fletch3555 
> can you elaborate on what you mean by "connection pool"

https://en.wikipedia.org/wiki/Connection_pool

> if you want multiple schemas, what's the harm in having a "tenant" connection point directly at it?

It's a complete disaster because I've at least 2000 tenant which means the app will reach `max_connection` easily because T/T creates a connection pool for each tenant (Laraval will throw `too many connections` error message)

**Comment by fletch3555** [comment]
Okay the link to wikipedia must be sarcasm (and if so, is not appreciated)... I obviously know what a connection pool is, but not how you've implemented it.  Also, don't be dramatic.. it's not a "disaster"

Also, what I don't understand is WHY you need a connection pool? Connection pools are useful in languages like java as those apps are often long-lived processes and therefore having a shared set of DB connections might be more efficient than connecting new each time.   Laravel on the other hand is bootstrapped fresh with each request.

A connection pool is typically configured with a set number of connections outside of the app logic, and the app is able to pull connections from that set or wait until one is available... so I'm not sure why you think tenancy is causing you to have 2000 connections in your pool.  But again, I have absolutely no idea how you've configured it.

And finally, using the example configuration in our docs, tenancy will reuse the "tenant" named connection for all tenant databases/schemas, depending on request context.  This is not conducive to connection pooling, unless it's handled at a higher level (i.e. the php runtime/PDO extension).

**Comment by mbnoimi** [comment]
> Okay the link to wikipedia must be sarcasm (and if so, is not appreciated)

Sorry I thought you really don't know what's the connection pool.

> Also, don't be dramatic.. it's not a "disaster"

Actually it is; Because when I launched my first test I noticed T/T creates a new connection for every tenant/request while I expected to see some connections!
As you can see in the screenshot (The 3rd field is for users while the 5th one is for schemas) there are many connections generated by T/T still alive (sleep) 
![image](https://user-images.githubusercontent.com/284547/108683822-2c172c80-7503-11eb-8e28-e736684a4fba.png)

> This is not conducive to connection pooling, unless it's handled at a higher level (i.e. the php runtime/PDO extension).

I use your example configs.

**Comment by fletch3555** [comment]
Please don't make me keep repeating myself.. how have you implemented connection pooling?

The screenshot you provided looks normal to me.  Those "sleep" connections are normal. There's a timeout period where connections are left there and closed but not cleaned up yet. They're there to be reused if needed within that time period.

From what I've read so far, I think this is one of 2 things:
1. Premature optimization.  You've seen all these sleeping connections and assumed it'll be a problem at scale, but have not actually seen it be a problem.
2. You're blaming the wrong thing.  Perhaps you just need to tune that timeout config (in php.ini, nothing to do with laravel or tenancy), or adjust the number of connections the DB can handle, or look at further load balancing techniques.  But I'd need to know a lot more about your implementation to provide anything remotely close to specific advice.

In any case, this is turning into a discussion and doesn't sound like it's actually tenancy related.  So I'm going to recommend moving to discord and closing this issue.  If we determine it's truly a tenancy issue, we'll reopen this and go from there.

**Comment by mbnoimi** [comment]
> how have you implemented connection pooling?

Sorry; This is right. 
I should publish my test on GitHub (actually I created the whole project on the VPS because I was using my tablet)
