### ISSUE TITLE
DB Connection set query grammar

### ISSUE THREAD

**Issue by chWagnr** [tenancy/tenancy#241]
Hi,

I need to change the default Laravel database connection query grammar:

```php
class AppServiceProvider extends ServiceProvider
{
    public function boot()
    {
        DB::connection()->setQueryGrammar(new JsonPathFixGrammar());
    }
}
``` 

But this sets it only for the default database connection. Not for the tenant's one. What's the best way to set it for the tenant?

**Comment by chWagnr** [comment]
Is this an option?
```php
Event::listen(function (\Tenancy\Affects\Connections\Events\Resolved $event) {
    Tenancy::getTenantConnection()->setQueryGrammar(new JsonPathFixGrammar());
});
```

**Comment by aislanfoina** [comment]
I know you can play with the tenant database connection based on event listeners, so it may be an option. You can listen ```Tenancy\Hooks\Database\Events\Drivers\Configuring``` to do somenthing when the tenant is created, or ```Tenancy\Affects\Connections\Events\Drivers\Configuring``` (check https://tenancy.dev/docs/tenancy/1.x/affects-connections) during the connection resolve. Hope it helps.

**Comment by ArlonAntonius** [comment]
Hey there,

Would like to add to that a little bit. Configuring might be a bit too early when it comes to creating the connection. There is a big chance that the connection will be deleted before it would get created.

I would recommend using the `Tenancy\Affects\Connections\Events\Resolved` event for this as you did in your example. If that does not work, feel free to let us know.

**Comment by chWagnr** [comment]
Thanks! Listening to `Tenancy\Affects\Connections\Events\Resolved` works perfect, but before setting the query grammar I had to check if a tenant is set.
