### ISSUE TITLE
How to setup landlord domain

### ISSUE THREAD

**Issue by Abbotton** [tenancy/tenancy#242]
Hi, there.

Basic info:

Main domain: `abc.test`.
Tenant domain: `tenant_one.abc.test`.
Tenant Identification: HTTP with sub-domain.
Visit tenant domain: successed.
Visit main domain: Fired `Tenancy\Identification\Events\NothingIdentified` event.

Question:
How to setup landlord domain?

Thanks.

**Comment by bkintanar** [comment]
@Abbotton this repository is for the https://tenancy.dev laravel package. I think your referring to the https://github.com/hipsterjazzbo/Landlord project

**Comment by luceos** [comment]
I am sorry @Abbotton do you still need an answer here? It's obvious your question relates to tenancy, considering the event class you've posted. The word Landlord has caused some confusion as this is the name of another multi tenant package.

It is not clear what exactly you're hoping to achieve, you have found the right event. So the next step would be activating different routes etc.

I'll be closing this issue, if there's anything we can do at this point, let us know.

**Comment by FupingGuo-at-poper** [comment]
It doesn't matter, I have solved this problem. Thank you very much for your reply 🤝 . @luceos

**Comment by Abbotton** [comment]
It doesn't matter, I have solved this problem. Thank you very much for your reply 🤝 . @luceos
