### ISSUE TITLE
doctrine/dbal:^3.0

### ISSUE THREAD

**Issue by chWagnr** [tenancy/tenancy#243]
Hi!
Is it possible to update to doctrine/dbal:^3.0?

Greetings

**Comment by luceos** [comment]
`tenancy/tenancy` 2.x will solve this; needs a tag first though.

**Comment by bkintanar** [comment]
@luceos tag added https://github.com/tenancy/tenancy/releases/tag/v2.0.0

**Comment by chWagnr** [comment]
Hi,

thanks for updating. Is it possible to update  doctrine/dbal it in [tenancy/db-driver-mysql](https://github.com/tenancy/db-driver-mysql) and [src/Database/Mysql/composer.json](https://github.com/tenancy/tenancy/blob/f97fe4efe951151377d72b340461ae2d34c1c32b/src/Database/Mysql/composer.json)?
