### ISSUE TITLE
Laravel 9

### ISSUE THREAD

**Issue by makroxyz** [tenancy/tenancy#244]
Any plans to add Laravel 9 support?

**Comment by builpro** [comment]
Not yet... 😢 

Problem 1
- tenancy/tenancy[v1.3.0, ..., 1.x-dev] require laravel/framework ^7.0 | ^8.0 -> found laravel/framework[v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^9.0).
- Root composer.json requires tenancy/tenancy ^1.3 -> satisfiable by tenancy/tenancy[v1.3.0, 1.x-dev].

**Comment by sniper7kills** [comment]
REL: #246

**Comment by luceos** [comment]
Fixed in #252, pending tag for 2.x
