### ISSUE TITLE
SQLite memory database and tenant migrations

### ISSUE THREAD

**Issue by djereg** [tenancy/tenancy#248]
__Description__

For testing I use SQLite and :memory: database. After I created the tenant, dispatch the [Created](https://github.com/tenancy/tenancy/blob/f97fe4efe951151377d72b340461ae2d34c1c32b/src/Tenancy/Tenant/Events/Created.php) event to run migrations. SQLite memory database keeps the data while the connection is alive, and creates new empty database each time a new connection is made.

The [MigratesHook](https://github.com/tenancy/tenancy/blob/f97fe4efe951151377d72b340461ae2d34c1c32b/src/Hooks/Migration/Hooks/MigratesHook.php) resolves the connection in [L67](https://github.com/tenancy/tenancy/blob/f97fe4efe951151377d72b340461ae2d34c1c32b/src/Hooks/Migration/Hooks/MigratesHook.php#L67) and after the migration is done, resets the connection in [L75](https://github.com/tenancy/tenancy/blob/f97fe4efe951151377d72b340461ae2d34c1c32b/src/Hooks/Migration/Hooks/MigratesHook.php#L75) ([sets the tenant database connection to null](https://github.com/tenancy/tenancy/blob/f97fe4efe951151377d72b340461ae2d34c1c32b/src/Affects/Connections/Listeners/SetConnection.php#L42) and [disconnects](https://github.com/tenancy/tenancy/blob/f97fe4efe951151377d72b340461ae2d34c1c32b/src/Affects/Connections/Listeners/SetConnection.php#L51)) so I have to reconnect to SQLite server which creates new empty database without any migrations done previously.

I did a workaround. Exteded the [MigratesHook](https://github.com/tenancy/tenancy/blob/f97fe4efe951151377d72b340461ae2d34c1c32b/src/Hooks/Migration/Hooks/MigratesHook.php) class and commented out [L75](https://github.com/tenancy/tenancy/blob/f97fe4efe951151377d72b340461ae2d34c1c32b/src/Hooks/Migration/Hooks/MigratesHook.php#L75) and it solved the problem, but I'm not sure that this is the correct solution. I woluld like to ask for some help. Maybe someon knows better how to solve the issue.

MariaDB and SQLite with file database works perfectly even after reconnecting. But SQLite with memory database is much faster during testing.

---
__Information__

- tenancy/tenancy version: 1.3.0
- laravel version: 8.83.10
- database driver and version: SQLite 3.34.1
- php version: 8.0.14

**Comment by luceos** [comment]
The extensible nature of tenancy helps here. We could change the behavior but it wouldn't make sense for just testing purposes I think unless there's a huge demand for it. Closing for now.
