### ISSUE TITLE
OnSystem on Tenant Model creates infinite loop

### ISSUE THREAD

**Issue by ArlonAntonius** [tenancy/tenancy#25]
At this moment when trying to identify a tenant by Http, it will cause an infinite loop and end up canceling the request eventually.

Use code is pretty simple and should always return the first tenant in the database.
```
   public function tenantIdentificationByHttp(Request $request) : ?TenantContract{
        \Log::info("In Tenant");
        return $this->newQuery()->first();
    }```

**Comment by luceos** [comment]
Is this happening on latest dev-master of tenancy/tenancy?

**Comment by ArlonAntonius** [comment]
All latest dev-master of:
Tenancy / Framework
Tenancy / DB-Driver-MySQL
Tenancy / Identification-Driver-HTTP

(Imported all packages on their own as it's the most towards a real-life situation.

**Comment by luceos** [comment]
@ArlonAntonius traced this to:

https://github.com/tenancy/framework/blob/6fc2a545e40c7bc604f3382ababf79e1e8cedaca/Identification/TenantResolver.php#L137

**Comment by ArlonAntonius** [comment]
This ended up being an issue with the `OnSystem` trait used on my tenant model.

**Comment by ArlonAntonius** [comment]
This issue would simply disappear if/when #26 gets merged.

**Comment by luceos** [comment]
The trait has been removed.
