### ISSUE TITLE
File system in Amazon S3

### ISSUE THREAD

**Issue by wdevmaster** [tenancy/tenancy#251]
Hello, how are you, I would like to know how to configure the tenant disk to be the amazon s3 disk so that I can upload all the files of my clients to that service.

Thank you.

**Comment by luceos** [comment]
The documentation shows how to configure a local filesystem. You can use any array that Laravel has in `filesystems.php` by default there: https://tenancy.dev/docs/tenancy/2.x/affects-filesystems
