### ISSUE TITLE
Mail::fake breaks on version 2.0

### ISSUE THREAD

**Issue by bretto36** [tenancy/tenancy#255]
__Description__

Had an issue today where after upgrading to 2.0 the Mail::fake calls would cause it to fail because we aren't enforcing a type of Illuminate\Contracts\Mail\Mailer instead it's using Illuminate\Mail\Mailer which the FakeMailer doesn't extend so it errors out. I switchted the type to Contract and it worked
..

---

__Actual behavior__

..

__Expected behavior__

..

---
__Information__

- tenancy/tenancy version:
- laravel version:
- database driver and version:
- webserver software and version:
- php version:

---

__tenancy.php config__

```php

```

---

__Error log__

```text

```

**Comment by luceos** [comment]
Without looking into this issue, could you provide pointers to our code to make things easier to fix?

Thanks for the report, this seems like something we should tackle soon.

**Comment by bretto36** [comment]
Apologies i can't replicate now. I was using individual packages, then switched to the tenancy/tenancy package and faced the issue. I've since switched back to the individual ones and it's all working fine. I wrote a test in my fork to try and prove it was broken but it was fine. 

It still might be worthwhile to switch to the Contract though. 

https://github.com/bretto36/tenancy/commit/15c4d43ba895e4913be388af1c3dc55af1f58a18#r76473433

**Comment by luceos** [comment]
I left a remark on that commit @bretto36 ; I think this needs a change.

**Comment by bretto36** [comment]
#256 here you go @luceos

**Comment by ArlonAntonius** [comment]
Fixed by #256
