### ISSUE TITLE
Vendor package to use tenant connection

### ISSUE THREAD

**Issue by FabriceAbbey** [tenancy/tenancy#260]
Hi, 

I am using this package https://github.com/spatie/laravel-permission for user permission and roles in my app for both the landlord and the tenant. On the landlord side everything works but on the tenant side it doesn't because it is using the landlord connection. I can not use the `onTenant `trait since it is a vendor package. Is it possible to switch the connection for the vendors to use the tenant connection when on a tenant subdomain ?

Thank you for this amazing package.

**Comment by luceos** [comment]
You'd best look into this one: https://tenancy.dev/docs/tenancy/2.x/affects-models

**Comment by FabriceAbbey** [comment]
Wow what dumb question I just asked thank you very much.
