### ISSUE TITLE
is not creating the database for tenancy

### ISSUE THREAD

**Issue by TranceDevCode** [tenancy/tenancy#262]
Hello, I have a project that stopped working the creation of the tenancy database, I did several tests but nothing works, the last thing I tried to do was try a new installation of laravel, I have made a clean installation of laravel and tenacy/tenancy 2.0, as well as with xampp, but the problem continues, definitely the problem seems to be somewhere else, not because of laravel or the library, deactivate antivirus but it continues, I don't know what else I could check, I'm on windows 10 21H2, please help me... Thank you guys

__Information__

- tenancy/tenancy version: 2.0
- laravel version: 9
- database driver and version:   10.4.24-MariaDB - mariadb.org binary distribution
- webserver software and version: xampp 3.3.0
- php version: 8.1.6

---

__tenancy.php config__

```php

```

---

__Error log__
I don't have error in log file.

**Comment by bkintanar** [comment]
Hi @TranceDevCode it's difficult to say where it went wrong since you don't have an error to show. Were you able to follow the docs in https://tenancy.dev? Have you reviewed the general setup guide there?

**Comment by luceos** [comment]
What user are you using for the tenancy connection, can you confirm it has elevated permissions to create databases and users?

**Comment by TranceDevCode** [comment]
I have this configuration guy 
@luceos i use the root user for develop, and i have this configuration file @bkintanar 
https://gist.github.com/TranceDevCode/8bf7f08c6ea4fa29010551f92b5cd7b3

**Comment by luceos** [comment]
Please stick to one channel of support:

https://discord.com/channels/146267795754057729/1014043445406466058/1014428995061817396

Issue seems to stem from using `tenancy/tenancy` which does not register any of the database drivers automatically to prevent two from being active at the same time.

I will add a warning to the Simplified Install section about this: https://tenancy.dev/docs/tenancy/2.x/installation#simplified-install
