### ISSUE TITLE
doctrine/dbal:^3.3 in MySQL driver

### ISSUE THREAD

**Issue by chWagnr** [tenancy/tenancy#269]
Hi,

is it possible to update doctrine/dbal it in [tenancy/db-driver-mysql](https://github.com/tenancy/db-driver-mysql) and [src/Database/Mysql/composer.json](https://github.com/tenancy/tenancy/blob/f97fe4efe951151377d72b340461ae2d34c1c32b/src/Database/Mysql/composer.json)?

**Comment by luceos** [comment]
What exactly is the reason for this?

**Comment by chWagnr** [comment]
I want to update doctrine/dbal but it does not work:
```
Problem 1
    - Root composer.json requires tenancy/db-driver-mysql ^2.0 -> satisfiable by tenancy/db-driver-mysql[v2.0.0, 2.x-dev].
    - tenancy/db-driver-mysql[v2.0.0, ..., 2.x-dev] require doctrine/dbal ^2.9 -> found doctrine/dbal[v2.9.0, ..., 2.13.9] but it conflicts with your root composer.json require (^3.3).
```

In tenancy/tenancy `composer.js` it's already `"doctrine/dbal": "^3.3"`
