### ISSUE TITLE
Question: should there be any upfront issue setting up tenancy with mongodb?

### ISSUE THREAD

**Issue by n3storm** [tenancy/tenancy#272]
We are planning to create a ngo federation software and tenancy package fits perfectly.

Also, ngo requirements are somewhat loose for many uncommon areas and going nosql is desired.

I could not find any issue or comment here in github nor googling mentioning **tenancy+mongdb**, thus our questions.

Anybody has managed this setup before? Does anybody feel there are going to appear many issues?

**Comment by mennovanhout** [comment]
You may need to write a database driver. But other then that it should be blocking.
https://tenancy.dev/docs/tenancy/2.x/database-drivers

**Comment by n3storm** [comment]
Thank you!
