### ISSUE TITLE
Queue Tenant Override Not Possible

### ISSUE THREAD

**Issue by ArlonAntonius** [tenancy/tenancy#29]
__Description__
In our vision, we had the idea to make all jobs tenant aware by default and have the possibility to override the identified tenant. This is for cases like a tenant being an "admin panel" and wanting to queue jobs for a specific tenant.

Automatic Tenancy for jobs is working fine after #28, however, you're not able to override the payload of a job by the looks of it. All variables get serialized into the data and not into the payload.

For references, a job contains of 2 major sets of information:
`Payload`: Containing information for the worker regarding the job
`Data`: Containing information for the job

![Example](https://i.gyazo.com/1e0bccf9509bdbd1adcea1998f41acbe.png)

---

__Actual behavior__
A job with the following payload:
```
[
  "displayName" => "Tenancy\Tests\Identification\Drivers\Queue\Mocks\Job"
  "job" => "Illuminate\Queue\CallQueuedHandler@call"
  "maxTries" => null
  "timeout" => null
  "timeoutAt" => null
  "data" => array:2 [
    "commandName" => "Tenancy\Tests\Identification\Drivers\Queue\Mocks\Job"
    "command" => "O:52:"Tenancy\Tests\Identification\Drivers\Queue\Mocks\Job":9:{s:9:"tenant_id";i:434571444;s:12:"tenant_class";s:28:"Tenancy\Testing\Mocks\Tenant";s:6:"\x00*\x00job";N;s:10:"connection";N;s:5:"queue";N;s:15:"chainConnection";N;s:10:"chainQueue";N;s:5:"delay";N;s:7:"chained";a:0:{}}"
  ]
]
```

__Expected behavior__
A job with the following payload:
```
[
  "displayName" => "Tenancy\Tests\Identification\Drivers\Queue\Mocks\Job"
  "job" => "Illuminate\Queue\CallQueuedHandler@call"
  "maxTries" => null
  "timeout" => null
  "timeoutAt" => null
  "data" => array:2 [
    "commandName" => "Tenancy\Tests\Identification\Drivers\Queue\Mocks\Job"
    "command" => "O:52:"Tenancy\Tests\Identification\Drivers\Queue\Mocks\Job":9:{s:9:"tenant_id";N;s:12:"tenant_class";N;s:6:"\x00*\x00job";N;s:10:"connection";N;s:5:"queue";N;s:15:"chainConnection";N;s:10:"chainQueue";N;s:5:"delay";N;s:7:"chained";a:0:{}}"
  ]
  "tenant_id" => 183898452
  "tenant_class" => "Tenancy\Testing\Mocks\Tenant"
]
```

---

__Error log__

```
1) Tenancy\Tests\Identification\Drivers\Queue\IdentifyInQueueTest::queue_wont_override_tenant
ErrorException: Undefined index: tenant_class
```

**Comment by ArlonAntonius** [comment]
## Update
After some research, I've figured out this is just straight up not possible at this moment. I'll try to break it down as good as I can.

### Payload hardcoding
At this moment Laravel has hardcoded the payload attributes, meaning we can't add any additional attributes. You can find the functions used for creating payloads [here](https://github.com/laravel/framework/blob/dbf5ced7605d61c2f3b62028f680f56e35db1f93/src/Illuminate/Queue/Queue.php#L121) and [here](https://github.com/laravel/framework/blob/dbf5ced7605d61c2f3b62028f680f56e35db1f93/src/Illuminate/Queue/Queue.php#L181).

### But we are mutating the payload in this package
Correct, as you can see, you can actually define callback functions that mutate the payload. We did this in order to make queue's tenant aware, it's an awesome feature by Laravel. However, you're not able to just add an attribute any other way.

### Solutions
Of course, I can talk about this being a huge problem, but let's start talking about possible solutions.
- Talk with the guys from Laravel to see if we can work something out that makes Queue more dynamic/hardcoded.
- Let the user provide the tenant_id in the data and read the tenant_id from there instead of from the payload. (Not the option I would go for, more on this later)

### Why we shouldn't use the data to define tenant information
One of the use cases we're keeping in mind with this is having one tenant (admin), queue jobs for another tenant. Let's say the admin tenant wants to send an email to the other tenant's admin related to maintenance.
The easiest way would be to create a job that automatically adds the admin tenant as the identified tenant, then inside the job add the tenant information inside the data, and simply use that.

The payload allows us to define attributes that the package needs without limiting the user to anything, I think we should aim for that.

**Comment by luceos** [comment]
Please check: https://github.com/tenancy/tenancy/commit/03621b5720fba5771344880a0e806a20c31c57f5

- Job will auto identify currently active tenant
- If job property `tenant_key` and `tenant_identifier` are set, these take precedence
- Rewrite some logic to use identifier/key and the TenantResolver as supposedly was the intention

Love to hear your opinion.

**Comment by luceos** [comment]
Is this issue and #28 still needed?

**Comment by ArlonAntonius** [comment]
I think we can close this for now, but let's revisit this one more time before the actual release of the package.
If Laravel adds a way to customize the payload from inside a job, I think we'd be better off using that.
