### ISSUE TITLE
ConfigureViews addPath() method with replace option sets config('view.paths') as string instead of array

### ISSUE THREAD

**Issue by ezp-matt** [tenancy/tenancy#298]
__Description__

The `Tenancy\Affects\Views\Events\ConfigureViews` class has a method called `addPath()` with a parameter `$replace` to replace the view paths with the specified path string.  That method sets the `view.paths` config value using the `config('view.paths')` helper, however it is setting that value as a string instead of an array.  This causes problems with Laravel classes such as `Illuminate\View\ViewServiceProvider` that read the `view.paths` config setting using the `config()` helper and expect it to be an array and not a string.

This line:

https://github.com/tenancy/tenancy/blob/05fc332761ece28a6820ecd32c7c0d8e1338608c/src/Affects/Views/Events/ConfigureViews.php#L40

...should actually be:

```php
config(['view.paths' => [$path]]);
```

When this is set incorrectly, calling (for example) `app('view.finder')` elsewhere in my application causes the following error:

```
Illuminate\View\FileViewFinder::__construct(): Argument #2 ($paths) must be of type array, string given, called in vendor/laravel/framework/src/Illuminate/View/ViewServiceProvider.php on line 84
```

The method causing the error in the `ViewServiceProvider` class is as follows:

```
    public function registerViewFinder()
    {
        $this->app->bind('view.finder', function ($app) {
            return new FileViewFinder($app['files'], $app['config']['view.paths']);
        });
    }
```
There are other Laravel classes that use this config setting as well.

---
__Information__

- tenancy/tenancy version: 2.2.0
- laravel version: 10.48.8
- webserver software and version: `php serve` (local development with laravel sail)
- php version: 8.1.27

---

__tenancy.php config__

using default config.

---

__Error log__

```text
Illuminate\View\FileViewFinder::__construct(): Argument #2 ($paths) must be of type array, string given, called in vendor/laravel/framework/src/Illuminate/View/ViewServiceProvider.php on line 84
```

**Comment by ArlonAntonius** [comment]
Thank you for letting us know about this error.

I just opened a PR (#300) to fix this issue. I'm going to look at what else might be slightly off here.

**Comment by ezp-matt** [comment]
Thanks for the fix!!
