### ISSUE TITLE
INDETIFIED BY causing problems

### ISSUE THREAD

**Issue by mgrom** [tenancy/tenancy#37]
Not a feature request, and not a bug (for now), but you shouldn't use IDENTIFIED BY in GRANT ALL statement. Correct usage is:
GRANT ALL PRIVILEGES ON database.* TO user@host;
Newest mysql versions don't accept IDENTIFIED BY in GRANT ALL, and for the older it is only usable when you want to change password in one statement.

"However, use of GRANT to create accounts or define nonprivilege characteristics is deprecated as of MySQL 5.7.6. Instead, perform these tasks using CREATE USER or ALTER USER."

**Comment by luceos** [comment]
We should be able to drop the IDENTIFIED BY, because this statement follows the CREATE USER statement. If you're up to it, feel free to remove that part in the MySQL driver, see if tests still are okay locally and PR the fix, we'll gladly merge.

**Comment by mgrom** [comment]
#39 fixed
