### ISSUE TITLE
Quarterly roadmaps

### ISSUE THREAD

**Issue by luceos** [tenancy/tenancy#6]
One of the organisational improvements I have been considering it to create a quarterly roadmap, in collaboration with @tenancy/team and the community. Aside from clear objectives for the package, it also allows for effort based payout which stimulates time investment into the package. Specifying goals per category well in advance allows team members (and even collaborators) to take ownership of their tasks.

The first thing to decide on is what this process for Quarterly Roadmaps looks like.

Some thoughts;

- [ ] Have staff members compile their draft todos.
- [ ] Discuss and improve the drafts as a team.
- [ ] Open up the draft roadmap to the public with a deadline.
- [ ] Once the deadline is reached, finalise and put them into separate issues.

**Comment by luceos** [comment]
Drafts of an actual roadmap, I currently can think of:

## Design

- [x] project identity
  - [x] logo
  - [x] color scheme
- [x] laravel-tenancy.com
  - [x] landing page
  - [x] documentation index
  - [x] documentation detail page
- [ ] Design merchandise (https://github.com/hyn/multi-tenant/issues/438)
  - [x] T-shirts
  - [x] Stickers
  - [ ] Mugs

## hyn/multi-tenant

- [ ] 5.2.x
  - [ ] add (blade) helpers
  - [x] make Website the tenant and not Hostname (NBC)
  - [x] add website listener to flush cache on crucial properties, see https://github.com/hyn/multi-tenant/issues/440

## tenancy/tenancy

- [ ] 1.0
  - [ ] tenant disk storage package
  - [ ] add caching were it makes sense
  - [x] mysql db driver
  - [x] http identification driver
  - [x] environment identification driver
  - [x] console identification driver
  - [ ] tenancy/framework code coverage to 70+ %
- [ ] 1.1
  - [ ] pgsql db driver
  - [ ] laravel spark driver
  - [ ] laravel gating/permissions driver
  - [ ] tenancy/framework code coverage to 80+ %

**Comment by johannesschobel** [comment]
Hey @luceos ,

i stumbled upon the `hyn/multi-tenant` package and was very impressed. When reading the docs on the website, I realized that there is another package `tenancy/tenancy` around the corner.

I tried to find some information about the "when can i use `tenancy/tenancy`" on the website, but was not able to find what i needed. I found a "complete project in 2018" note, however.

Do you have any estimated time-frames when a `1.0` version may be available for use? How hard will it be to upgrade from `hyn/multi-tenant` to `tenancy/tenancy`? Will there be a migration guide?

All the best and thanks for this awesome project,
cheers

**Comment by luceos** [comment]
Hello @johannesschobel ,

Glad to hear you like it!

There's currently no pressure to release tenancy in a stable form. Although I've been picking up quite a steady pace in terms of development, I've been revisiting many of the previous assumptions and implementations. A stable version 1.0 will only be released when I can guarantee the most fluent upgrade from hyn and a feature complete cloud-focused saas toolkit. This still might result in some features not being portable, most of the local filesystem functionality (described under [structure in the docs](https://laravel-tenancy.com/docs/hyn/5.2/structure)) will most likely not be part of the default tenancy toolkit. Possibly there will be an adapter for the lost functionality.

An upgrade guide will be provided.

**Comment by intellow** [comment]
Hi @luceos ,

I am very excited for your release of Tenancy 1.0 as well. I am starting a new project in the next few weeks and plan to use your package. It sounds like it will be a while before 1.0 gets here, so I guess I will start with hyn. Thanks for a great product and good luck with everything!

**Comment by luceos** [comment]
Hello @intellow,

Thanks for your kind words! Let us know if you need any assistance with the implementation 👍

**Comment by johannesschobel** [comment]
Hey @luceos , thank you very much for your answer on the "release topic".

Say, you would need to start developing a new SAAS application in about 3 months from now on (late october), would you start with `hyn` or `tenancy`? What are the odds, that `tenancy` is within a `stable 1.0` release state till then?

Thank you very much for your awesome work and time.. I really (!!!) really appreciate it!
All the best

**Comment by luceos** [comment]
@johannesschobel chances are tenancy might be stable by then.. Or not. If you start developing in 3 months, you should check back on the status around that time.

I am currently working on a demo project called [restaurateur.app](https://github.com/tenancy/restaurateur.app) which is meant as a background story for the new docs. If you'd ask me with what I would build a new saas, it would be tenancy for that reason. I would need to confirm it works after all.

**Comment by johannesschobel** [comment]
damn, that was a fast response :laughing: I just got my coffee and had an answer, that is awesome..

yeah, i stumbled upon this repo yesterday, when i was trying to find appropriate information / details on this project. I have a request in this regard: Would it be possible for you to add a `laravel passport` integration? I think, this is the "way to go" for most applications developed with laravel for obvious reasons ;)

**Comment by bkintanar** [comment]
It (passport integration support) was in my todo list months ago, but got distracted with other things. Looks like I need that doc finished up, for obvious reasons.

--
Bertrand Kintanar
bertrand.kintanar@gmail.com

**Comment by luceos** [comment]
@bkintanar the request here relates to tenancy/tenancy not so much hyn/multi-tenant, correct @johannesschobel ?

One of the goals of tenancy is to become far easier to interact with other existing packages. Passport is obviously one of them. However, passport can also be run differently in multi tenancy; create clients on each tenant or create clients on the system to be used by the tenant..

**Comment by johannesschobel** [comment]
oh man.. if you could write a respective tutorial / doc chapter i would be very thankful. I would also donate a few bucks via paypal ;)

**Comment by johannesschobel** [comment]
@luceos , sorry, i missed your answer - shame on me..
The "how to use passport" is actually related to both (tenancy and hyn) packages ;)

**Comment by intellow** [comment]
@luceos I will let you know if I need any help (which I probably will). I figure I'll jump in the Discord chat once I really get started. My plan is to start building the core functionality with Spark and then add multi-tenancy later. Would that work or do I need to start with your package from the beginning?

**Comment by johannesschobel** [comment]
from what i read / think of the package, i would rather start with tenant-related stuff first @intellow .. but that is just my guess :laughing:

**Comment by albertosgz** [comment]
Hi @luceos.
Your projects look awsome in many aspects, helping us to develop very easy and fast new applications.
As people said, regarding to start a new project, I am interested on use your tenancy package very soon. Is there any update about when will be release an stable version of the tenancy/tenancy project?

**Comment by luceos** [comment]
No not yet, but the best way to spur development on is to pledge to it, I know this sounds cheesy but I do need to make a living as well. You can back us over at https://opencollective.com/tenancy

I am still trying to hold onto my deadline of releasing tenancy/tenancy this year. But I've also decided to push one of my own side projects out first to get a little buffer onto the family finances (see how this works 😏).

I am aware people are waiting for this, yet so far Hyn/multi-tenant is also a perfect candidate for building SaaS. For cloud based versions I'd guess tenancy/tenancy will be on a different playing field altogether though.

**Comment by d8vjork** [comment]
@luceos Can help in both sides (pledge and code), same as many people told here, want this to release (already start a big project using hyn) and want to change to this as soon as possible

**Comment by luceos** [comment]
@d8vjork Hello Ruben, thanks for your commitment, to be honest with @ArlonAntonius recently joining the team we've made huge progress in both packages, especially with tenancy. There are a few ways to further speed up getting to stable with this package:

- join our discord and help us test tenancy/tenancy and each package separately.
- support us on our open collective.
- start building apps with the current version, report issues you find and possibly start creating PR's in close collaboration with us. Please note the bridge isn't ready yet.

At the current pace I assume we can come up with a beta within one or two months.

**Comment by d8vjork** [comment]
@luceos Nice to hear that!

I'm doing the last, start testing with a fresh Laravel installation and checking docs. I saw about the bridge, I'll take it for my current projects
