### ISSUE TITLE
Pull request docs and template

### ISSUE THREAD

**Issue by luceos** [tenancy/tenancy#60]
An idea I had to be transparent about our Pull Request processes is to create a documentation item about it. In addition we can add comments in the template. An example:

---

### Tests

- [ ] provided in the pull request. 
_Pull requests that include tests are merged faster as they can be reviewed more easily. Take a look at how we write and review tests in our [docs](#)._

**Comment by luceos** [comment]
I think it would be possible to add another docs section, just like one of the packages. 🤔

**Comment by pmccarren** [comment]
Hi @luceos! I'd like to help and build out the Postgres DB driver, however I'm not exactly sure where to submit PR's to.. Should they be submitted to tenancy/tenancy, tenancy/db-driver-X, or perhaps a different location? 

Cheers!

**Comment by checkerschaf** [comment]
@pmccarren As mentioned in the contributions part of the readme file: 
Contributors need to use this repository for implementing code. All other repositories are READ-ONLY and overwritten on each subsplit push. :)

**Comment by pmccarren** [comment]
@checkerschaf ah apologies, I totally missed that. Thanks for the info :)

**Comment by luceos** [comment]
Made a beginning at some governance information a while ago: https://laravel-tenancy.com/docs/governance/tenancy/pull-requests
