### ISSUE TITLE
Landing Page Banner Concept

### ISSUE THREAD

**Issue by paulotra** [tenancy/tenancy#7]
I need some help regarding the banner for the landing page, some thoughts and idea would be very helpful. Here's the current one i've been working on...

<img width="1399" alt="screen shot 2018-05-15 at 9 27 34 am" src="https://user-images.githubusercontent.com/20724804/40031432-41eaddfa-5822-11e8-8f9e-61778abf0b53.png">

The given illustration isn't really fitting the product, so we're looking for some inspiration what to put in its place. We want the best result for the landing page so any suggestions would be very helpful.

**Comment by skyrpex** [comment]
Perhaps this needs to display multiple servers (the tenants) connected to a single source of truth (the source code, or the library itself)?

**Comment by paulotra** [comment]
@skyrpex i'll give that a shot, good idea.

@luceos What do you think?

**Comment by luceos** [comment]
The concept of showing a single source of truth with tenants as a result is great, but I think we need to know the direction the illustration has to be designed in. Something more detailed 👍 

I've been considering something like a huge flat, with condos representing tenants and the outline of the building described as Tenancy.

**Comment by luceos** [comment]
some inspiration while looking around

![image](https://user-images.githubusercontent.com/504687/40880679-af745562-66b5-11e8-85ea-f2539cf5a521.png)
![image](https://user-images.githubusercontent.com/504687/40880685-d150e934-66b5-11e8-8bf9-206d0fe37209.png)
![image](https://user-images.githubusercontent.com/504687/40880686-db1eb450-66b5-11e8-9174-0f980f5d65a5.png)
![image](https://user-images.githubusercontent.com/504687/40880695-e6d64628-66b5-11e8-99ea-525eb2354583.png)
![image](https://user-images.githubusercontent.com/504687/40880700-ee82ec5a-66b5-11e8-88e5-d8d126645f67.png)

**Comment by paulotra** [comment]
Nice, maybe we could apply some to our website

**Comment by luceos** [comment]
@paulotra i like the first one a lot; the warm tone of the building, but it could use some more height to make it stand out more? Would you be able to create something from this, it won't need to be that detailed.

**Comment by paulotra** [comment]
Sure, where do you want this to be added? So that i can opportune it
