### ISSUE TITLE
Can't install the package

### ISSUE THREAD

**Issue by amargoCactus** [tenancy/tenancy#72]
__Description__

I want to implement tenancy/tenancy package but it gives an error when installing it

---

__Information__

- laravel version: 5.8
- database driver and version: mariadb 10.1.32
- webserver software and version: apache 2.4
- php version: 7.2.5

---

__Error log__

`In ProviderRepository.php line 208:`
`Class 'Tenancy\Affects\Migrations\Providers\ServiceProvider' not found`
`Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1`
`Installation failed, reverting ./composer.json to its original content.`

![error-tenancy-package](https://user-images.githubusercontent.com/36394543/59441063-f9c4aa80-8dc5-11e9-9382-0feba6cf113a.PNG)

```

**Comment by zhuzhichao** [comment]
@s9ul3ss #71 will fix the namespace issue. wait for merging.  😃
